//! Query API — iterate over entities possessing a specific component set.
//!
//! Queries borrow archetypes immutably (read) or exclusively (write).
//! The type system enforces that a world borrow used for reads cannot
//! simultaneously be used for writes to the same component.

use std::marker::PhantomData;

/// Marker trait for component types.
///
/// Implemented automatically for any `'static + Send + Sync` type.
/// Components must be `Send + Sync` so that systems can run on any thread.
pub trait Component: 'static + Send + Sync {}
impl<T: 'static + Send + Sync> Component for T {}

/// A typed query over components `T`.
///
/// Concrete implementation is generated by the `world.query::<T>()` API;
/// this struct is the public iterator surface.
pub struct Query<T>(PhantomData<T>);
